import { Resume } from '@/types/resume.types';
import { FileEdit, FilePlus2, LayoutTemplate, Zap } from 'lucide-react';

export const actions = [
  {
    title: 'Build from scratch',
    description:
      'Start fresh and create a standout resume step by step. Our guided assistant helps you write every section with confidence.',
    icon: FilePlus2,
    route: '/app/resumes/create',
    className: {
      card: 'hover:border-blue-500/50',
      iconWrapper: 'bg-blue-50 border border-blue-200',
      icon: 'text-blue-600',
    },
  },
  {
    title: 'Improve existing resume',
    description:
      'Already have a resume? Upload it and we’ll enhance formatting, clarity, and impact to make it recruiter-ready.',
    icon: FileEdit,
    route: '/app/my-resumes',
    className: {
      card: 'hover:border-emerald-500/50',
      iconWrapper: 'bg-emerald-50 border border-emerald-200',
      icon: 'text-emerald-600',
    },
  },
  {
    title: 'Optimize for job description',
    description:
      'Target a specific job by pasting the description. We’ll tailor your resume to match keywords and pass ATS filters.',
    icon: Zap,
    route: '/app/job-optimizer',
    className: {
      card: 'hover:border-amber-500/50',
      iconWrapper: 'bg-amber-50 border border-amber-200',
      icon: 'text-amber-600',
    },
  },
  {
    title: 'Use template',
    description:
      'Choose from professionally designed templates tailored for different industries and experience levels.',
    icon: LayoutTemplate,
    route: '/app/templates',
    className: {
      card: 'hover:border-purple-500/50',
      iconWrapper: 'bg-purple-50 border border-purple-200',
      icon: 'text-purple-600',
    },
  },
];
export const CURRENT_RESUMES: Resume[] = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    targetJob: 'Google / Meta',
    lastModified: '2026-03-25',
    score: 92,
    isPrimary: true,
  },
  {
    id: '2',
    title: 'Frontend Developer',
    targetJob: 'Startup / Series A',
    lastModified: '2026-03-18',
    score: 78,
  },
  {
    id: '3',
    title: 'Frontend Developer',
    targetJob: 'Amazon',
    lastModified: '2026-03-10',
    score: 64,
  },
  {
    id: '4',
    title: 'Fullstack Developer (Node/React)',
    targetJob: 'Fintech',
    lastModified: '2026-02-28',
    score: 88,
  },
  {
    id: '5',
    title: 'Backend Engineer',
    targetJob: 'Stripe / Payments',
    lastModified: '2026-02-20',
    score: 81,
  },
  {
    id: '6',
    title: 'React Developer',
    targetJob: 'Product Company',
    lastModified: '2026-02-12',
    score: 74,
  },
  {
    id: '7',
    title: 'Software Engineer Intern',
    targetJob: 'FAANG Internship',
    lastModified: '2026-01-30',
    score: 69,
  },
  {
    id: '8',
    title: 'Fullstack Engineer',
    targetJob: 'Early Stage Startup',
    lastModified: '2026-01-22',
    score: 85,
  },
  {
    id: '9',
    title: 'Frontend Engineer (React)',
    targetJob: 'Design-focused Company',
    lastModified: '2026-01-15',
    score: 77,
  },
  {
    id: '10',
    title: 'Node.js Developer',
    targetJob: 'Backend-heavy Role',
    lastModified: '2025-12-28',
    score: 80,
  },
  {
    id: '11',
    title: 'Software Engineer',
    targetJob: 'MNC',
    lastModified: '2025-12-10',
    score: 72,
  },
  {
    id: '12',
    title: 'Frontend Developer (Next.js)',
    targetJob: 'Remote Startup',
    lastModified: '2025-11-25',
    score: 83,
  },
  {
    id: '13',
    title: 'Fullstack Developer',
    targetJob: 'SaaS Company',
    lastModified: '2025-11-10',
    score: 87,
  },
  {
    id: '14',
    title: 'UI Engineer',
    targetJob: 'Design Systems Team',
    lastModified: '2025-10-28',
    score: 75,
  },
  {
    id: '15',
    title: 'Junior Developer',
    targetJob: 'Entry Level Role',
    lastModified: '2025-10-15',
    score: 68,
  },
];

export type Job = {
  jobId: string;
  company: string;
  jobTitle: string;
  status: 'applied' | 'interview' | 'offer' | 'rejected';
  dateApplied: string;
  salaryRange?: string;
  followUpReminder?: string;
  location: string;
  recruiterName?: string;
  jobListingUrl?: string;
  notes?: string;
};

export const jobData: Job[] = [
  {
    jobId: '1',
    company: 'Google',
    jobTitle: 'Frontend Developer',
    status: 'interview',
    dateApplied: '2026-03-20',
    salaryRange: '₹15L - ₹25L',
    followUpReminder: '2026-04-15',
    location: 'Bangalore, India',
    recruiterName: 'Priya Sharma',
    jobListingUrl: 'https://careers.google.com/jobs/123',
    notes: '2nd round scheduled',
  },
  {
    jobId: '2',
    company: 'Amazon',
    jobTitle: 'SDE I',
    status: 'applied',
    dateApplied: '2026-04-01',
    salaryRange: '₹12L - ₹20L',
    followUpReminder: '2026-04-18',
    location: 'Hyderabad, India',
    recruiterName: 'Rahul Verma',
    jobListingUrl: 'https://amazon.jobs/456',
    notes: 'Waiting for response',
  },
  {
    jobId: '3',
    company: 'Microsoft',
    jobTitle: 'Software Engineer',
    status: 'offer',
    dateApplied: '2026-03-10',
    salaryRange: '₹18L - ₹30L',
    followUpReminder: '2026-04-12',
    location: 'Noida, India',
    recruiterName: 'Anjali Mehta',
    jobListingUrl: 'https://careers.microsoft.com/789',
    notes: 'Offer received, negotiating',
  },
  {
    jobId: '4',
    company: 'Flipkart',
    jobTitle: 'React Developer',
    status: 'rejected',
    dateApplied: '2026-02-25',
    salaryRange: '₹10L - ₹18L',
    location: 'Bangalore, India',
    recruiterName: 'Karan Gupta',
    jobListingUrl: 'https://flipkartcareers.com/101',
    notes: 'Rejected after tech round',
  },
  {
    jobId: '5',
    company: 'Meta',
    jobTitle: 'Frontend Engineer',
    status: 'interview',
    dateApplied: '2026-03-28',
    salaryRange: '₹20L - ₹35L',
    followUpReminder: '2026-04-20',
    location: 'Remote',
    recruiterName: 'Sneha Kapoor',
    jobListingUrl: 'https://meta.com/careers/202',
    notes: 'Initial screening cleared',
  },
  {
    jobId: '6',
    company: 'Netflix',
    jobTitle: 'UI Engineer',
    status: 'applied',
    dateApplied: '2026-04-05',
    salaryRange: '₹25L - ₹40L',
    followUpReminder: '2026-04-22',
    location: 'Remote',
    recruiterName: 'Amit Singh',
    jobListingUrl: 'https://jobs.netflix.com/303',
    notes: 'Application submitted',
  },
  {
    jobId: '7',
    company: 'Adobe',
    jobTitle: 'Frontend Developer',
    status: 'interview',
    dateApplied: '2026-03-18',
    salaryRange: '₹16L - ₹28L',
    followUpReminder: '2026-04-16',
    location: 'Noida, India',
    recruiterName: 'Ritika Jain',
    jobListingUrl: 'https://adobe.com/careers/404',
    notes: 'Tech interview pending',
  },
  {
    jobId: '8',
    company: 'Uber',
    jobTitle: 'Software Engineer I',
    status: 'applied',
    dateApplied: '2026-04-02',
    salaryRange: '₹14L - ₹22L',
    followUpReminder: '2026-04-19',
    location: 'Bangalore, India',
    recruiterName: 'Vikas Reddy',
    jobListingUrl: 'https://uber.com/careers/505',
    notes: 'Waiting for recruiter response',
  },
  {
    jobId: '9',
    company: 'Swiggy',
    jobTitle: 'React Native Developer',
    status: 'interview',
    dateApplied: '2026-03-30',
    salaryRange: '₹12L - ₹20L',
    followUpReminder: '2026-04-21',
    location: 'Bangalore, India',
    recruiterName: 'Neha Agarwal',
    jobListingUrl: 'https://careers.swiggy.com/606',
    notes: 'HR round completed',
  },
  {
    jobId: '10',
    company: 'Zomato',
    jobTitle: 'Frontend Engineer',
    status: 'rejected',
    dateApplied: '2026-03-05',
    salaryRange: '₹10L - ₹18L',
    location: 'Gurgaon, India',
    recruiterName: 'Arjun Malhotra',
    jobListingUrl: 'https://zomato.com/careers/707',
    notes: 'Rejected after assignment',
  },
  {
    jobId: '11',
    company: 'Paytm',
    jobTitle: 'Software Developer',
    status: 'offer',
    dateApplied: '2026-03-12',
    salaryRange: '₹14L - ₹24L',
    followUpReminder: '2026-04-14',
    location: 'Noida, India',
    recruiterName: 'Pooja Saxena',
    jobListingUrl: 'https://paytm.com/careers/808',
    notes: 'Offer received, reviewing',
  },
  {
    jobId: '12',
    company: 'Razorpay',
    jobTitle: 'Frontend Engineer',
    status: 'interview',
    dateApplied: '2026-03-25',
    salaryRange: '₹15L - ₹26L',
    followUpReminder: '2026-04-17',
    location: 'Bangalore, India',
    recruiterName: 'Manish Tiwari',
    jobListingUrl: 'https://razorpay.com/jobs/909',
    notes: 'Coding round cleared',
  },
  {
    jobId: '13',
    company: 'Infosys',
    jobTitle: 'Systems Engineer',
    status: 'applied',
    dateApplied: '2026-04-08',
    salaryRange: '₹6L - ₹10L',
    followUpReminder: '2026-04-25',
    location: 'Pune, India',
    recruiterName: 'Deepak Nair',
    jobListingUrl: 'https://infosys.com/careers/111',
    notes: 'Application under review',
  },
  {
    jobId: '14',
    company: 'TCS',
    jobTitle: 'Software Engineer',
    status: 'applied',
    dateApplied: '2026-04-10',
    salaryRange: '₹5L - ₹9L',
    followUpReminder: '2026-04-27',
    location: 'Mumbai, India',
    recruiterName: 'Shalini Deshpande',
    jobListingUrl: 'https://tcs.com/careers/222',
    notes: 'No update yet',
  },
  {
    jobId: '15',
    company: 'Wipro',
    jobTitle: 'Frontend Developer',
    status: 'rejected',
    dateApplied: '2026-02-20',
    salaryRange: '₹5L - ₹8L',
    location: 'Chennai, India',
    recruiterName: 'Suresh Iyer',
    jobListingUrl: 'https://wipro.com/careers/333',
    notes: 'Rejected after HR round',
  },
];

export const STATUS_CONFIG = {
  applied: {
    label: 'Applied',
    color: 'bg-blue-100 text-blue-600',
    bar: 'bg-blue-500',
    hover: 'hover:bg-blue-400 hover:text-white',
  },
  interview: {
    label: 'Interview',
    color: 'bg-orange-100 text-orange-600',
    bar: 'bg-orange-500',
    hover: 'hover:bg-orange-400 hover:text-orange-50',
  },
  offer: {
    label: 'Offer',
    color: 'bg-green-100 text-green-600',
    bar: 'bg-green-500',
    hover: 'hover:bg-green-500 hover:text-green-50',
  },
  rejected: {
    label: 'Rejected',
    color: 'bg-red-100 text-red-600',
    bar: 'bg-red-500',
    hover: 'hover:bg-red-500 hover:text-red-50',
  },
} as const;
