import type { Metadata } from 'next';
import {
  geistSans,
  geistMono,
  orbitron,
  roboto,
  rajdhani,
  montserrat,
  exo_2,
  ibm_plex_mono,
  poppins,
} from '@/app/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${roboto.variable} ${rajdhani.variable} ${montserrat.variable} ${exo_2.variable} ${ibm_plex_mono.variable} ${poppins.variable} h-full scroll-smooth antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
